name: Spigot-HologramUILib
version: '1.0.0'
main: fr.perrier.hologramuilib.HologramUILibPlugin
description: Spigot API for HologramUILib - Create interactive holographic menus in Minecraft
api-version: '1.20'

authors:
  - Perrier

website: https://github.com/CodeAndCup/HologramUILib
commands:
  hologramenu:
    description: HologramUILib command (debug/admin)
    usage: /hologramenu <subcommand>
    permission: hologramuilib.admin

permissions:
  hologramuilib.admin:
    description: Admin permissions for HologramUILib
    default: op
